version: '3.4'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: nestTgGpt
        ports:
            - "27017:27017"
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - "./dbdata:/data/db"
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    dev:
        build:
            context: .
            target: nestjs-dev
        container_name: server-dev
        ports:
            - "3000:3000"
        environment:
            - ENV=dev
        volumes:
            - "./:/usr/src/app/"
        command: "yarn run start:dev"
        depends_on:
            mongo:
                condition: service_healthy
