version: '3.4'

services:
    server:
        build:
            context: .
            target: nestjs-prod
        environment:
            - ENV=production
        command: "yarn run start:prod"
        extra_hosts:
            - 'mongo:192.168.1.199'
        volumes:
            - ./logs:/home/logs

