version: '3.4'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - "./dbdata:/data/db"
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    server:
        build:
            context: .
            target: nestjs-prod
        ports:
            - "8080:3000"
        environment:
            - ENV=production
        command: "yarn run start:prod"
        depends_on:
            mongo:
                condition: service_healthy
